[package]
name = "thumbnail-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
image = "0.25.6"
rayon = "1.10.0"

[[bin]]
name = "thumbnail"
path = "src/main.rs"
